version: '3.1'
services:
  minecraft-exporter:
    image: 'joshi425/minecraft_exporter'
    environment:
      RCON_HOST: 
      RCON_PORT:
      RCON_PASSWORD:
    ports:
    - 9700:8000
    volumes:
    - minecraft-data:/mcdata:ro

volumes:
  minecraft-data:
    external: true
